services:
  - type: web
    name: farm-backend
    env: docker
    dockerfilePath: ./farm-backend/Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: farm-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true

databases:
  - name: farm-db
    plan: free
    databaseName: farm_management
